### PR TITLE
Write student backend & fix bug related to users definition

### LINKED ISSUE #24: Task.07.2 - Backend: QR code validation API
- Accept uploaded QR image file.
- Decode QR and verify ticket validity.
- Mark ticket as checked in.

### LINKED ISSUE #45: Task.01.2 - Backend: Events API
- Implement endpoint to fetch events. 
- Add filtering support. Filters: date, category, organization

### LINKED ISSUE #46: Task.01.3 - Backend: Search logic
- Implement keyword search that goes through both titles and descriptions.
- Show no results message when no events match filter and/or search.

### LINKED ISSUE #53: Task.03.1 - Backend: Ticket claim API
- Endpoint for claiming tickets
- Validate event capacity before issuing ticket.
- Check event capacity before issuing ticket

Ideal Hours: 4h

### LINKED ISSUE #56: Task.04.1 - Backend: Generate Ticket QR code
Implement so that on claim, generate a QR code with the student and event details.

### LINKED ISSUE #60: Task.04.3 - Backend: Ticket retrieval API
- Endpoint to fetch ticket details + QR code

### LINKED ISSUE #82: Bugfix #1: Update backend to stop requiring organizer pending status

### LINKED ISSUE #84: Task.02.6 - Backend: Download event to default calendar API
- Endpoint to download an ICS file containing calendar event data

Ideal Hours: 4h

### PR DESCRIPTION
**Pull request by othmaneelhajhouj**
Fixes #82 (bug 1) 
- Makes organizerStatus optional in schema but required for for users with the organizer role
- organizerStatus initializes to pending on user's promotion to organizer, and clears on demotion (related moderation fields too)

Resolves #46 (task 01.3)
- Adds keyword searching for title and description
- Retruns pagination metadata: page, limit, total, pages, sort, order, filters
- Tested, works as expected

Partly resolves #45 (task 01.2)
- Adds optional filters to GET /events. Filters: from/to, category (exact), org, search, page/limit/sort/order
- Tested, works as expected

Resolves #84 (task 02.6)
- Downloads an ICS file which adds the event to the device's default calendar app (should be automatic on mobile devices and macOS, need to click the file on windows)
- Tested, works as expected

Resolves #53 (task 03.1)
- Adds tickets route & ticketService service, handles free/paid & claimed/used status for tickets
- Validates event capacity before issuing ticket
- Tested, works as expected

Resolves #56 (task 04.1)
- Adds get ticket method that returns qr code in png format
- Important: returns 404 if user isnt admin or ticket owner
- Tested, works as expected

Resolves #60 (task 04.3)
- Adds get ticket method that returns ticket details
- Important: returns 404 if user isnt admin or ticket owner
- Tested, works as expected

Resolves #24 (tast 07.2)
- Adds post organizers method to validate given QR if QR token belongs to even
- Adds post organizers method to scan, decode and validate QR
- Tested, works as expected

### CODE REVIEW

File: Sprint2/app/src/routes/organizerScan.ts [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+    } catch(e) {
+        console.error("QR token scan failed!", e);
+        return res.status(500).json({error: "Server error."});
+    }
+});
+
+//POST /organizers/:organizerID/events/:eventId/scan-image
+organizerScan.post("/organizers/:organizerId/events/:eventId/scan-image", upload.single("image"), async(req: Request, res: Response) => {
+    try {
+        const {organizerID, eventId} = req.params;
```
Comment (WTV26) [inline Sprint2/app/src/routes/organizerScan.ts]: the route param is organizerId. Your code is using organizerID

File: Sprint2/app/src/routes/organizerScan.ts [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+
+}
+
+//detect json response preference helper, used in POST
+function wantsJson(req: Request) {
+    const accept = req.headers.accept || "";
+    const ct = req.headers["content-type"] || "";
+    return (
+        (typeof accept === "string" && accept.includes("application/json")) ||
+        (typeof ct === "string" && ct.includes("a^^mication/json"))
```
Comment (WTV26) [inline Sprint2/app/src/routes/organizerScan.ts]: What's a^^mication? Typo?

**Review by WTV26 — CHANGES_REQUESTED** [review]
- [ ] Hard‑coded seed-dependent IDs: the temporary auth middleware pins to a cuid that changes whenever the DB is reseeded, so flows will start erroring.

- [ ] Organizer scan and ticket claim: the scan-image route reads the wrong param name and the JSON detection typo causes HTML errors.

- [ ] Date filtering, JSON payloads, and ICS export are breaking or malformed: the student events handler rejects [to] filters, mislabels response JSON (i.e [date] vs [data]), and escapes commas incorrectly in ICS files.

File: Sprint2/app/src/services/adminRoleManagementService.ts [hunk 3]
```diff
@@ -28,6 +28,12 @@ export async function setRole({adminId, userId, role,} :
             where: {id: userId},
             data: {
                 role,
+                organizerStatus: role === "organizer" ? "pending" : null,
+                ...(role !== "organizer" ? {
+                    approvedBy: null,
+                    approvedAt: null,
+                    decisionReason: null
+                }: {}),
```
[the remark this answers is not in the document]
Comment (othmaneelhajhouj) [reply Sprint2/app/src/services/adminRoleManagementService.ts]: did not touch the logic here
